### PR TITLE
Rough in wiring to optionally destroy content outside the viewbox

### PR DESCRIPTION
**Pull request by rsheeter**
First pass at a fix for #200. Requires https://github.com/googlefonts/picosvg/pull/146.

### CODE REVIEW

**Comment by rsheeter** [comment]
I need the fast CI here too lol

**Comment by anthrotype** [comment]
> I need the fast CI here too lol

I know.. Today I finished touching up the picosvg CI setup. I think I like it now. Initially I had two separate workflows (distinct yaml configs for the tests and the deployment), but now I merged them in to a single worfklow. This way when we `git push --follow-tags` to make a release, it first runs all the tests (the same as with regular pushes) and only if all tests pass, it creates the Github Release and uploads the distribution packages to PyPI. Before the two test and deploy worfklows were independent from one another, and it might happen that the wheel builds but the tests fail and you end up publishing a broken package.

I will update the googlefonts/python docs tomorrow so you can try doing the same for nanoemoji.

**Review by anthrotype — APPROVED** [review]
LGTM

**Comment by rsheeter** [comment]
Seems to help rendering considerably to not have bizarre nonsense outside the rendering area. Curiously it seems like the emoji I was testing didn't have crazy stuff but others in the font did and that was enough to make things go awry.

*Before, canvas 3705.4 x 1080.8*

```xml
  <head>
    <xMin value="-9824"/>
    <yMin value="-2408"/>
    <xMax value="16747"/>
    <yMax value="6238"/>

  <hhea>
    <minLeftSideBearing value="-9824"/>
    <minRightSideBearing value="-15723"/>
    <xMaxExtent value="16747"/>
```

image

*After, canvas 512.6 x 128.0*

```xml
  <head>
    <xMin value="-2"/>
    <yMin value="0"/>
    <xMax value="1027"/>
    <yMax value="1024"/>

  <hhea>
    <minLeftSideBearing value="-2"/>
    <minRightSideBearing value="-998"/>
    <xMaxExtent value="1027"/>
```

image

**Comment by rsheeter** [comment]
Made some of our files smaller too which is nice :)

```
 fonts/noto-cff2_colr_1.otf               | Bin 3002612 -> 2976012 bytes
 fonts/noto-cff_colr_1.otf                | Bin 3449160 -> 3416684 bytes
 fonts/noto-glyf_colr_1.ttf               | Bin 3826288 -> 3778192 bytes
 fonts/noto-picosvg.ttf                   | Bin 18771972 -> 18561436 bytes
 fonts/noto-picosvgz.ttf                  | Bin 4557516 -> 4498080 bytes
```

**Comment by anthrotype** [comment]
Wow `3826288 - 3778192 = 48,096`.. is that 48 Kb of junk?

**Pull request merged**
