### PR TITLE
fix transform for untouchedsvg output

### PR DESCRIPTION
**Pull request by anthrotype**
When we build OT-SVG with `--color_format=untouchedsvg` we are not correctly positioning the SVG in the OT-SVG space. We need to use the same method that we use for the `picosvg` output for mapping from viewBox to OT-SVG space.

Originally reported by @yisibl in https://github.com/googlefonts/nanoemoji/issues/266#issuecomment-816715374

He confirmed (in private chat) that this fixes the positioning issue in Safari/Firefox.

### CODE REVIEW

**Comment by anthrotype** [comment]
It may also be that adding a `transform` directly to the root `<svg>` element like we are currently doing was the cause of the issue that @yisibl reported (I believe it was with the Safari browser).

In any case, adding a wrapping `<g>` group with a glyph `id` and a `transform` attributes is also what we are already doing for the `--color_format-picosvg` and that works, so for consistency we should do the same for `untouchedsvg` like in this PR.

**Comment by anthrotype** [comment]
Plus, this PR also makes sure that the `untouchedsvg` output will behave the same way as `picosvg` and `colr_1` outputs with regards to the scaling/positioning of the SVG in the (ascender-descender) height and the glyph advance width. The naive translation that we are currently doing for  `untouchedsvg` did not take that into account.

**Review by rsheeter — APPROVED** [review]

**Comment by yisibl** [comment]
Thanks for such a quick fix.

**Comment by anthrotype** [comment]
Thank you for reporting and testing this!

**Pull request merged**
