### PR TITLE
use pip to install precompiled resvg wheel

### PR DESCRIPTION
**Pull request by anthrotype**
Towards fixing #372

### CODE REVIEW

**Comment by anthrotype** [comment]
seems to be working somehow, because cargo now compains that resvg exists already:
https://github.com/googlefonts/nanoemoji/runs/4872442013?check_suite_focus=true#step:6:10

**Comment by anthrotype** [comment]
seems like it worked for linux at least: 

> Ignored package `resvg v0.20.0` is already installed

but on windows the cache never hits, and the rust build is the one taking the longest.. Maybe the cargo directory lives in a different path on windows filesystem? or maybe i'm missing something else.

**Comment by yisibl** [comment]
I have developed a resvg package for use in node.js that might solve the slow build problem in CI. This package does exactly the same thing as resvg's rendering.

You can try it out, there is no command line mode yet, but I can implement it.

**Comment by anthrotype** [comment]
@yisibl thanks, but I don't think using node.js is a good idea for a python project. Maybe I'll try to use https://github.com/PyO3/maturin to package up the resvg binary crate in a python wheel so I can just use pip to install.

**Comment by yisibl** [comment]
@anthrotype Got it. pyo3 is great.

**Comment by anthrotype** [comment]
I created a new github repo called https://github.com/anthrotype/resvg-wheels and used maturin to make resvg wheels for all platforms and uploaded them to Github Releases. So now we can do `pip install --find-links https://github.com/anthrotype/resvg-wheels/releases/tag/v0.2.0 resvg` and pip will download the right wheel from Github.

I didn't publish the wheels to PyPI just yet, I'd like to first ask the resvg authors for their consent.
But for the sake of our own test suite, I'd say this beats the slow cargo install by a great margin (from several minutes to a couple seconds) so I'd merge this for now.

**Pull request merged**
