### PR TITLE
Emit scale around center where appropriate

### PR DESCRIPTION
**Pull request by rsheeter**
Take advantage of PaintScaleAroundCenter where possible

### CODE REVIEW

**Comment by rsheeter** [comment]
Expected - but not verified in a real Noto compile - benefits outlined in https://github.com/googlefonts/nanoemoji/issues/316#issuecomment-894865790.

**Comment by anthrotype** [comment]
one problem with replacing general PaintTransform with specialized PaintScaleAroundCenter is that the latter uses integers for the (cx, cy) center coordinates, so if you pass a float value then fontTools will round it to int as it compiles the PaintScaleAroundCenter.
E.g. your code converts `Affine2D(a=0.117, b=0, c=0, d=0.117, e=44.167, f=44.167)` to:

```python
cx = cy = 50.01925254813137
Affine2D.identity().translate(cx, cy).scale(0.117, 0.117).translate(-cx, -cy)
```
However when 50.01925254813137 becomes 50, the combination of translate, scale and counter-translate equals to `Affine2D(a=0.117, b=0.0, c=0.0, d=0.117, e=44.15, f=44.15)` , so there will be a ~= 0.017 translation delta in both x and y that is basically lost to rounding.

I guess we can deem that acceptable and live with it..

**Comment by rsheeter** [comment]
> integers for the (cx, cy) center coordinates

Ah good catch, that's a bug in how I did this

**Comment by rsheeter** [comment]
Added test + fix for the int'ness of cx, cy

**Review by anthrotype — APPROVED** [review]

**Pull request merged**
